# Generated by Django 4.2.3 on 2023-07-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_alter_verifyemailtoken_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifyemailtoken',
            old_name='email',
            new_name='user',
        ),
    ]
