# Generated by Django 4.2.3 on 2023-07-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentgame_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescategory',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Категория'),
        ),
    ]
