# Generated by Django 4.2.3 on 2023-07-14 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentgame_app', '0002_alter_gamescategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentgame_app.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='game',
            name='pledge',
            field=models.IntegerField(verbose_name='Залог'),
        ),
    ]
