# Generated by Django 4.2.3 on 2023-07-16 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentgame_app', '0003_alter_game_city_alter_game_pledge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Объявление по продаже игр', 'verbose_name_plural': 'Объявления по продаже игр'},
        ),
        migrations.AlterModelOptions(
            name='gamescategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории игр'},
        ),
        migrations.AlterModelOptions(
            name='gamesplatform',
            options={'verbose_name': 'Игровая платформа', 'verbose_name_plural': 'Игровые платформы'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='image',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='games_images', verbose_name='Изображение')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentgame_app.game', verbose_name='Объявления')),
            ],
        ),
    ]
