# Generated by Django 4.2.3 on 2023-07-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentgame_app', '0004_alter_city_options_alter_game_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, upload_to='games_images', verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
