# Generated by Django 4.2.3 on 2023-07-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentgame_app', '0006_remove_game_image_gameimage_game_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='games_images', verbose_name='Изображение')),
            ],
        ),
        migrations.DeleteModel(
            name='GameImage',
        ),
        migrations.AlterField(
            model_name='game',
            name='images',
            field=models.ManyToManyField(blank=True, to='rentgame_app.gameimages', verbose_name='Изображения'),
        ),
    ]
