# Generated by Django 4.2.3 on 2023-07-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentgame_app', '0007_gameimages_delete_gameimage_alter_game_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='images',
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, upload_to='games_images', verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='GameImages',
        ),
    ]
